### ISSUE TITLE
Crashes writing files on 64 bit 4D V14

### ISSUE THREAD

**Issue by leehinde** [miyako/4d-plugin-xls#1]
Windows 4D Server(64bit) crashes on XLS WORKBOOK Save document

C_LONGINT($success)
C_TEXT($doc_name)

$doc_name:=Get 4D folder(Current resources folder)+Generate UUID+".xls"

$success:=XLS WORKBOOK Save document ($book;$doc_name)

The document is created but it has no content.

Works fine locally on my Mac. And works fine on Windows if I use non-64bit Server.

**Comment by miyako** [comment]
the behaviour should be now the same 64-bit (16R4) but there is still a problem with Unicode data (no problems with path)

**Comment by miyako** [comment]
the unicode problem should be solved now
