### ISSUE TITLE
Formula in cell

### ISSUE THREAD

**Issue by AlfonsoIdem** [miyako/4d-plugin-xls#3]
Hello.
Is there any way to create a cell with a formula like:
=N7+T7

**Comment by miyako** [comment]
what have tried so far ?

**Comment by AlfonsoIdem** [comment]
$textXls:="=N"+String($rowSel)+"+T"+String($rowSel)
$cell:=XLS WORKSHEET Set cell text($sheet; $row; $Col; $format; $textXls)

But it does not recognize it as a formula

$textXls:="=N"+String($rowSel)+"+T"+String($rowSel)
$cell:=XLS WORKSHEET Set cell fn($sheet; $row; $Col; $format; $textXls)

It does nothing.

**Comment by miyako** [comment]
I am not sure but I think it is **not** possible. expression like "=A1+B1" must be parsed and analysed. it doesn't have any special meaning as text.

looking at the source, it seems like the `binary_op_node_t` class is used to construct a non-formula expression. 

I don't use this plugin myself, perhaps you can search the internet for xlslib examples, but you might not find much discussion. 

.xls (BIFF) has been out of fashion for nearly 20 years.
